# Generated by Django 2.2.9 on 2021-08-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('comment', models.CharField(max_length=50, verbose_name='Коментарий')),
                ('published', models.DateField(verbose_name='Опубликовано')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
