# Generated by Django 2.2.9 on 2021-08-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
