# Generated by Django 2.2.9 on 2021-08-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210814_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calc',
            options={'verbose_name_plural': 'Значения'},
        ),
        migrations.AlterField(
            model_name='calc',
            name='ammount',
            field=models.IntegerField(verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='calc',
            name='comment',
            field=models.CharField(max_length=100, verbose_name='Коментарий'),
        ),
    ]
