# Generated by Django 2.2.9 on 2021-08-13 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210814_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calc',
            old_name='date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='calc',
            old_name='comment',
            new_name='text',
        ),
    ]
