# Generated by Django 2.2.9 on 2021-08-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210814_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calc',
            old_name='text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='calc',
            old_name='pub_date',
            new_name='date',
        ),
    ]
