# Generated by Django 2.2.9 on 2021-08-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210814_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
